### ISSUE TITLE
two issues in v0.6.0 

### ISSUE THREAD

**Issue by chrjxj** [NVIDIA/GenerativeAIExamples#126]
Issue 1 - chain-server

SW version: v0.6.0

```

Traceback (most recent call last):
  File "/usr/local/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/main.py", line 416, in main
    run(
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/main.py", line 587, in run
    server.run()
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/config.py", line 467, in load
    self.loaded_app = import_from_string(self.app)
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/RetrievalAugmentedGeneration/common/server.py", line 27, in <module>
    from pymilvus.exceptions import MilvusException, MilvusUnavailableException
  File "/usr/local/lib/python3.10/dist-packages/pymilvus/__init__.py", line 26, in <module>
    from .bulk_writer.remote_bulk_writer import (
  File "/usr/local/lib/python3.10/dist-packages/pymilvus/bulk_writer/remote_bulk_writer.py", line 18, in <module>
    from minio import Minio
  File "/usr/local/lib/python3.10/dist-packages/minio/__init__.py", line 41, in <module>
    from .api import Minio
  File "/usr/local/lib/python3.10/dist-packages/minio/api.py", line 44, in <module>
    from urllib3.response import BaseHTTPResponse
ImportError: cannot import name 'BaseHTTPResponse' from 'urllib3.response' (/usr/local/lib/python3.10/dist-packages/urllib3/response.py)
```

Issue 2 - deploy/compose/rag-app-text-chatbot.yaml

docker env got error and suggest ENABLE_TRACING should be int ,string or null
```
      ENABLE_TRACING: null
```

**Comment by chrjxj** [comment]
for issues 1 , i added one line in dockerfile to workaround . fyi. 

```

# Copy required common modules for all examples
COPY RetrievalAugmentedGeneration/__init__.py /opt/RetrievalAugmentedGeneration/
COPY RetrievalAugmentedGeneration/common /opt/RetrievalAugmentedGeneration/common
COPY integrations /opt/integrations
COPY tools /opt/tools

RUN pip uninstall urllib3 && pip install --upgrade urllib3

```
