### ISSUE TITLE
When I run /RetrievalAugmentedGeneration/examples/developer_rag/chains

### ISSUE THREAD

**Issue by Suiji12** [NVIDIA/GenerativeAIExamples#158]

**Comment by Suiji12** [comment]
I  met a error:C:\Users\jiaojiaxing\.conda\envs\localgpt\python.exe E:\jiaojiaxing\GenerativeAIExamples\RetrievalAugmentedGeneration\examples\developer_rag\chains.py  C:\Users\jiaojiaxing\.conda\envs\localgpt\lib\site-packages\langchain_nvidia_ai_endpoints\_common.py:172: UserWarning: An API key is required for the hosted NIM. This will become an error in the future.   warnings.warn( C:\Users\jiaojiaxing\.conda\envs\localgpt\lib\site-packages\langchain_nvidia_ai_endpoints\_common.py:172: UserWarning: An API key is required for the hosted NIM. This will become an error in the future.   warnings.warn( Traceback (most recent call last):   File "E:\jiaojiaxing\GenerativeAIExamples\RetrievalAugmentedGeneration\examples\developer_rag\chains.py", line 40, in <module>     set_service_context()   File "E:\jiaojiaxing\GenerativeAIExamples\RetrievalAugmentedGeneration\common\utils.py", line 115, in wrapper     return func(*args_hashable, **kwargs_hashable)   File "E:\jiaojiaxing\GenerativeAIExamples\RetrievalAugmentedGeneration\common\utils.py", line 122, in set_service_context     llm = LangChainLLM(get_llm(**kwargs))   File "E:\jiaojiaxing\GenerativeAIExamples\RetrievalAugmentedGeneration\common\utils.py", line 115, in wrapper     return func(*args_hashable, **kwargs_hashable)   File "E:\jiaojiaxing\GenerativeAIExamples\RetrievalAugmentedGeneration\common\utils.py", line 265, in get_llm     return ChatNVIDIA(model=settings.llm.model_name,   File "C:\Users\jiaojiaxing\.conda\envs\localgpt\lib\site-packages\langchain_nvidia_ai_endpoints\chat_models.py", line 243, in __init__     self._client = _NVIDIAClient(   File "C:\Users\jiaojiaxing\.conda\envs\localgpt\lib\site-packages\langchain_nvidia_ai_endpoints\_common.py", line 213, in __init__     raise ValueError( ValueError: Model ensemble is unknown, check `available_models`  Process finished with exit code 1
